News_Portal/News/urls.py
from django.urls import path
# Импортируем созданное нами представление
from .views import PostsList, PostDetail, PostSearch, PostCreate, PostUpdate, PostDelete, ArticleCreate, ChoosePostType, \
   CategoryListView, subscribe, trigger_error
from .views import IndexView
from django.views.decorators.cache import cache_page



urlpatterns = [
   # path — означает путь.
   # В данном случае путь ко всем товарам у нас останется пустым,
   # чуть позже станет ясно почему.
   # Т.к. наше объявленное представление является классом,
   # а Django ожидает функцию, нам надо представить этот класс в виде view.
   # Для этого вызываем метод as_view.
   #path('', Posts.as_aview),
   path('', PostsList.as_view(), name='post_list'),
   # pk — это первичный ключ товара, который будет выводиться у нас в шаблон
   # int — указывает на то, что принимаются только целочисленные значения
   path('<int:pk>/', PostDetail.as_view(), name='post_detail'),
   path('search/', PostSearch.as_view(), name='post_search'),
   path('create/', PostCreate.as_view()),
   path('<int:pk>/update/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('news/create/', PostCreate.as_view(), name='news_create'),
   path('articles/create/', ArticleCreate.as_view(), name='article_create'),
   path('choose/', ChoosePostType.as_view(), name='choose_post_type'),
   path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
   path('index/', IndexView.as_view()),
   path('trigger-error/', trigger_error),  # Маршрут для вызова ошибки



]

News_Portal/News_Portal/urls.py
from django.contrib import admin
from django.urls import path, include
from News.views import trigger_error  # Импортируем trigger_error из приложения News


urlpatterns = [
    path("admin/", admin.site.urls),
    #path('pages/', include('django.contrib.flatpages.urls')),
    #path('posts/', include('News.urls')),
    path('news/', include('News.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
    path('trigger-error/', trigger_error),  # Маршрут для вызова ошибки



]

News_Portal/News/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import pgettext_lazy


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        post_rating = sum(post.rating * 3 for post in self.post_set.all())
        comment_rating = sum(comment.rating for post in self.post_set.all() for comment in post.comment_set.all())
        self.rating = post_rating + comment_rating
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    POST_TYPE_CHOICES = [
        ('article', 'Статья'),
        ('news', 'Новость'),
    ]
    post_type = models.CharField(max_length=7, choices=POST_TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    # time_in = models.DateTimeField(auto_now_add=True, verbose_name=pgettext_lazy('Time_in', 'Time_in'))
    date_published = models.DateTimeField(default=timezone.now)
    categories = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    content = models.TextField()
    rating = models.IntegerField(default=0)

    def preview(self):
        return self.content[:124] + '...' if len(self.content) > 124 else self.content

    def like(self):
        self.rating += 1
        self.save()


    def dislike(self):
        self.rating -= 1
        self.save()

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.title.title()}: {self.content[:500]}'


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.category)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"

News_Portal/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Статья</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

News_Portal/templates/category_list.html
<html>
<head>
    <title>{{ category.name }}</title>
</head>
<body>
    <h1>Категория: {{ category.name }}</h1>
    <p>
        {% if is_not_subscriber %}
            <a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a>
        {% else %}
            Вы подписаны на эту категорию.
        {% endif %}
    </p>
    <ul>
        {% for post in posts %}
            <li><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

News_Portal/templates/choose_post_type.html
{% extends 'flatpages/default.html' %}

{% block content %}
  <h1>Выберите тип поста</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit" name="post_type" value="article">Создать статью</button>
    <button type="submit" name="post_type" value="news">Создать новость</button>
  </form>
{% endblock %}

News_Portal/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
    <ul>
        {% for post in posts %}
            <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

News_Portal/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

News_Portal/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}  <!-- Загрузка файла с фильтрами, замените на ваше название -->

{% block content %}
{% if post %}
<table>
    <tr>
        <td>Название</td>
        <td>Дата публикации</td>
        <td>Описание</td>
        <td>Категория</td>
    </tr>
    <tr>
        <td>{{ post.title|censor }}</td> <!-- Применение фильтра censor к заголовку -->
        <td>{{ time_now|date:"d M Y" }}</td> <!-- Формат даты для каждой новости -->
        <td>{{ post.content|censor }}</td> <!-- Применение фильтра censor к содержанию новости -->
        <td>
            {% for category in post.categories.all %}
            {{ category.name }}
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </td>
    </tr>
</table>
{% else %}
<h2>Новостей нет!</h2>
{% endif %}
{% endblock content %}

News_Portal/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

News_Portal/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Вышла новая  <a href="{{  link }}">статья в вашем подписанном разделе</a></h2>
    <p>{{ text|truncatechars:50 }}</p>
</body>
</html>

News_Portal/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.title }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

News_Portal/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Редактировать пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock %}

News_Portal/templates/post_limit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1> Уважаемый {{author}}, публиковать больше трех новостей в сутки нельзя!!!</h1>>
{% endblock content%}

News_Portal/templates/post_search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
<h1>Введите данные для поиска!</h1>

<form action="" method="get">
    {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
    {{ filterset.form.as_p }}


    {# Добавим кнопку отправки данных формы #}
    <input type="submit" value="Найти" />
</form>

<hr>

<h1>Все новости</h1>

<p><strong>Общее количество новостей:</strong> {{ posts|length }}</p>
<hr>

{% if posts %}
    <table>
        <tr>
            <td>Название</td>
            <td>Дата публикации</td>
            <td>Описание</td>
            <td>Категория</td>
        </tr>
        {% for post in posts %}
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.created_at|date:"d M Y H:i:s" }}</td> <!-- Формат даты для каждой новости -->
                <td>{{ post.content|truncatewords:20 }}</td>
                <td>
                {% for category in post.categories.all %}
                {{ category.name }}{% if not forloop.last %}, {% endif %} <!-- Выводим все категории через запятую -->
            {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <h2>Новостей нет!</h2>
{% endif %}

{# Добавляем пагинацию #}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>  {# ссылка на первую страницу #}
    {% if page_obj.previous_page_number != 1 %}
        ...  {# многоточие, если номер предыдущей страницы не 1 #}
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>  {# ссылка на предыдущую страницу #}
    {% endif %}
{% endif %}

{{ page_obj.number }}  {# отображение номера текущей страницы #}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>  {# ссылка на следующую страницу #}
    {% if paginator.num_pages != page_obj.next_page_number %}
        ...  {# многоточие, если номер следующей страницы не равен общему количеству страниц #}
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>  {# ссылка на последнюю страницу #}
    {% endif %}
{% endif %}
{% endblock content %}

News_Portal/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{{ article_title|censor }}</title>
    </head>
    <body>
        <h1>{{ article_title|censor }}</h1>
        <p>{{ article_content|censor }}</p>
    </body>
    </html>

    <h1>Все новости</h1>

    <p><strong>Общее количество новостей:</strong> {{ posts|length }}</p>
    <hr>
    {% if posts %}
        <table>
            <tr>
                <td>Название</td>
                <td>Дата публикации</td>
                <td>Описание</td>
                <td>Категория</td>
                <td>Тип публикации</td>

            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.title }}</td>
                    <td>{{ post.created_at|date:"d M Y H:i:s" }}</td> <!-- Формат даты для каждой новости -->
                    <td>{{ post.content|truncatewords:20 }}</td>
                    <td>
                {% for category in post.categories.all %}
                    {{ category.name }}{% if not forloop.last %}, {% endif %} <!-- Выводим все категории через запятую -->
                {% endfor %}

                   </td>
                    <td>{{ post.get_post_type_display }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

    {# Добавляем пагинацию #}
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>  {# ссылка на первую страницу #}
        {% if page_obj.previous_page_number != 1 %}
            ...  {# многоточие, если номер предыдущей страницы не 1 #}
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>  {# ссылка на предыдущую страницу #}
        {% endif %}
    {% endif %}

    {{ page_obj.number }}  {# отображение номера текущей страницы #}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>  {# ссылка на следующую страницу #}
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...  {# многоточие, если номер следующей страницы не равен общему количеству страниц #}
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>  {# ссылка на последнюю страницу #}
        {% endif %}
    {% endif %}
{% endblock content %}

News_Portal/templates/your_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Custom Template Tags Example</title>
</head>
<body>
    {% load custom_extras %}

    <p>{{ "Это пример текста с нежелательное слово в нем" | hide_forbidden }}</p>
</body>
</html>